### ISSUE TITLE
[吐槽]现在开发版内测换公测刷不进去了

### ISSUE THREAD

**Issue by fredomne** [FlyGoat/miui_ota_to_fastbootd#7]
想着退了内测刷公测，迟迟不推送，找了卡刷包(V13.0.5.1.5.DEV)试试老办法。结果开头在fastboot这段全部失败，好像都是文件不存在，之后卡在了dsp_a一直不动，我就强制停下了。好在因为都是失败了所以原系统(22.2.7)也还在，没砖。
是否说明现在的开发版公测已经和内测的文件有很大不同了...
现在也没有内测名额了，不想清数据老实线刷就只能偷渡内测或者卡在这个版本了貌似

**Comment by fredomne** [comment]
线刷了开发版公测之后再用咱们这边工具刷内测包，除了卡了一处（cpucp卡很久，直接拔线重连继续脚本）一切又都正常了。
不过公测和内测确实不通了（应用都打不开），但是借助作者的工具成功回到之前的同版本内测了，数据未丢失，乐。
唯一一个报错就是fastboot: error: cannot load 'images\vm-bootsys.img': No such file or directory。无伤大雅。

**Comment by FlyGoat** [comment]
现在其实可以root之后手动用update_engine_client刷。
